locals {
  pipeline_types = {
    build_ecr = {
      file_path      = "ci-pipelines/build-gitlab.ci.yaml"
      job_name       = "build"
      extends        = ".build"
      commit_message = "Add reusable build_ecr GitLab CI pipeline"

      include = {
        project = "das-meta/gitlab-ci-templates"
        ref     = "DMVP-1150"
        file    = "/ci-templates/templates/build/ecr-buildx.gitlab-ci.yml"
      }

      default_variables = {
        IMAGE_TAG       = "$CI_COMMIT_SHORT_SHA"
        DOCKERFILE_PATH = "Dockerfile"
        BUILD_CONTEXT   = "."
      }

      variable_order = [
        "AWS_REGION",
        "IMAGE_REPOSITORY",
        "IMAGE_TAG",
        "DOCKERFILE_PATH",
        "BUILD_CONTEXT",
        "BUILD_ARGS",
        "BUILDX_CREATE_ARGS",
      ]

      variable_keys = {
        aws_region         = "AWS_REGION"
        image_repository   = "IMAGE_REPOSITORY"
        image_tag          = "IMAGE_TAG"
        dockerfile_path    = "DOCKERFILE_PATH"
        build_context      = "BUILD_CONTEXT"
        build_args         = "BUILD_ARGS"
        buildx_create_args = "BUILDX_CREATE_ARGS"
      }
    }
  }

  normalized_ci_pipelines = flatten([
    for p in var.gitlab_projects : [
      for pipeline in try(p.gitlab_ci_pipelines, []) : {
        key            = "${p.name}:${pipeline.type}"
        project_name   = p.name
        type           = pipeline.type
        config         = local.pipeline_types[pipeline.type]
        variables      = try(pipeline.variables, {})
        target_branch  = coalesce(try(p.default_branch, null), "main")
        source_branch  = "terraform/ci-pipelines/${replace(pipeline.type, "_", "-")}"
        create_mr      = coalesce(try(pipeline.create_merge_request, null), true)
        commit_message = coalesce(try(pipeline.commit_message, null), local.pipeline_types[pipeline.type].commit_message)
        mr_title       = coalesce(try(pipeline.merge_request_title, null), local.pipeline_types[pipeline.type].commit_message)
        remove_branch  = coalesce(try(pipeline.remove_source_branch, null), true)
        file_path      = coalesce(try(pipeline.file_path, null), local.pipeline_types[pipeline.type].file_path)
        job_name       = coalesce(try(pipeline.job_name, null), local.pipeline_types[pipeline.type].job_name)
        ci_variables = merge(
          local.pipeline_types[pipeline.type].default_variables,
          {
            for source_key, target_key in local.pipeline_types[pipeline.type].variable_keys :
            target_key => try(pipeline.variables, {})[source_key]
            if try(try(pipeline.variables, {})[source_key], null) != null
          }
        )
        template = {
          project = coalesce(try(pipeline.template_project, null), local.pipeline_types[pipeline.type].include.project)
          ref     = coalesce(try(pipeline.template_ref, null), local.pipeline_types[pipeline.type].include.ref)
          file    = coalesce(try(pipeline.template_file, null), local.pipeline_types[pipeline.type].include.file)
        }
      } if contains(keys(local.pipeline_types), pipeline.type)
    ]
  ])

  ci_pipeline_files = {
    for pipeline in local.normalized_ci_pipelines : pipeline.key => {
      project_name   = pipeline.project_name
      target_branch  = pipeline.target_branch
      source_branch  = pipeline.create_mr ? pipeline.source_branch : pipeline.target_branch
      create_mr      = pipeline.create_mr
      commit_message = pipeline.commit_message
      mr_title       = pipeline.mr_title
      mr_description = <<-EOT
        This merge request adds a reusable ${pipeline.type} pipeline wrapper generated by Terraform.

        It creates `${pipeline.file_path}`. That file includes the shared GitLab CI template from `${pipeline.template.project}` and defines the `${pipeline.job_name}` job with project-specific variables.

        To use it, keep your root `.gitlab-ci.yml` or `.gitlab-ci.yaml` manually owned and add this include:

        ```yaml
        include:
          - local: ${pipeline.file_path}
        ```

        After that, GitLab will load the generated wrapper pipeline, which includes the shared reusable `.build` template and runs the generated `${pipeline.job_name}` job.
      EOT
      remove_branch  = pipeline.remove_branch
      file_path      = pipeline.file_path
      content = join("\n", concat(
        [
          "include:",
          "  - project: ${pipeline.template.project}",
          "    ref: ${pipeline.template.ref}",
          "    file: ${pipeline.template.file}",
          "",
          "${pipeline.job_name}:",
          "  extends: ${pipeline.config.extends}",
          "  variables:",
        ],
        [
          for variable_name in pipeline.config.variable_order :
          "    ${variable_name}: ${pipeline.ci_variables[variable_name]}"
          if contains(keys(pipeline.ci_variables), variable_name)
        ],
        [""]
      ))
    }
  }

  gitlab_merge_request_command = <<-SH
    python3 <<'PY'
    import json
    import os
    import sys
    import urllib.error
    import urllib.parse
    import urllib.request

    token = os.environ.get("GITLAB_API_TOKEN") or os.environ.get("GITLAB_TOKEN")
    if not token:
        print("ERROR: set GITLAB_API_TOKEN or GITLAB_TOKEN so Terraform can create the GitLab merge request", file=sys.stderr)
        sys.exit(1)

    api_url = os.environ["GITLAB_API_URL"].rstrip("/")
    project = urllib.parse.quote(os.environ["GITLAB_PROJECT"], safe="")
    source_branch = os.environ["GITLAB_SOURCE_BRANCH"]
    target_branch = os.environ["GITLAB_TARGET_BRANCH"]
    title = os.environ["GITLAB_MR_TITLE"]
    description = os.environ["GITLAB_MR_DESCRIPTION"]
    remove_source_branch = os.environ.get("GITLAB_REMOVE_SOURCE_BRANCH", "true").lower() == "true"
    headers = {"PRIVATE-TOKEN": token, "Content-Type": "application/json"}

    def request(method, path, payload=None):
        data = None if payload is None else json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(api_url + path, data=data, headers=headers, method=method)
        try:
            with urllib.request.urlopen(req, timeout=30) as response:
                body = response.read().decode("utf-8")
                return json.loads(body) if body else None
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            print(f"ERROR: GitLab API {method} {path} failed: {exc.code} {body}", file=sys.stderr)
            sys.exit(1)

    query = urllib.parse.urlencode({
        "state": "opened",
        "source_branch": source_branch,
        "target_branch": target_branch,
    })
    existing = request("GET", f"/projects/{project}/merge_requests?{query}") or []
    payload = {
        "source_branch": source_branch,
        "target_branch": target_branch,
        "title": title,
        "description": description,
        "remove_source_branch": remove_source_branch,
    }
    if existing:
        iid = existing[0]["iid"]
        request("PUT", f"/projects/{project}/merge_requests/{iid}", payload)
        print(f"Updated existing merge request !{iid}")
    else:
        created = request("POST", f"/projects/{project}/merge_requests", payload)
        print("Created merge request !%s" % created.get("iid"))
    PY
  SH
}

resource "gitlab_branch" "ci_pipeline" {
  for_each = {
    for key, file in local.ci_pipeline_files : key => file
    if file.create_mr
  }

  project = var.project_ids[each.value.project_name]
  name    = each.value.source_branch
  ref     = each.value.target_branch
}

resource "gitlab_repository_file" "ci_pipeline" {
  for_each = local.ci_pipeline_files

  project = var.project_ids[each.value.project_name]

  file_path = each.value.file_path
  branch    = each.value.source_branch
  content   = each.value.content
  encoding  = "text"

  commit_message      = each.value.commit_message
  overwrite_on_create = true

  depends_on = [gitlab_branch.ci_pipeline]
}

resource "null_resource" "ci_pipeline_merge_request" {
  for_each = {
    for key, file in local.ci_pipeline_files : key => file
    if file.create_mr
  }

  triggers = {
    project_id    = tostring(var.project_ids[each.value.project_name])
    source_branch = each.value.source_branch
    target_branch = each.value.target_branch
    title         = each.value.mr_title
    description   = each.value.mr_description == null ? "" : each.value.mr_description
    remove_branch = tostring(each.value.remove_branch)
    file_path     = each.value.file_path
    file_content  = each.value.content
  }

  provisioner "local-exec" {
    command = local.gitlab_merge_request_command
    environment = {
      GITLAB_API_URL              = "https://gitlab.com/api/v4"
      GITLAB_PROJECT              = self.triggers.project_id
      GITLAB_SOURCE_BRANCH        = self.triggers.source_branch
      GITLAB_TARGET_BRANCH        = self.triggers.target_branch
      GITLAB_MR_TITLE             = self.triggers.title
      GITLAB_MR_DESCRIPTION       = self.triggers.description
      GITLAB_REMOVE_SOURCE_BRANCH = self.triggers.remove_branch
    }
  }

  depends_on = [gitlab_repository_file.ci_pipeline]
}
